services:
  dxspider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dxspider
    restart: unless-stopped
    ports:
      # --- USER TELNET PORTS (Forwarded to Internal 7300 - 'dx' handler) ---
      #- "23:7300"     # Standard Telnet
      - "7300:7300"   # DXSpider User Default
      #- "7373:7300"   # Alternative User Port
      # --- DEDICATED NODE PORTS (Forwarded to Internal 8001 - 'node' handler) ---
      #- "3607:8001"   # K3LR / Incoming ARCluster Node Port
      - "8001:8001"   # DXSpider Node Default
      # --- Web Telnet Terminal ---
      - "8080:8080"
    volumes:
      - ./local:/spider/local
      - ./local_data:/spider/local_data
      - ./connect:/spider/connect
      - ./local_cmd:/spider/local_cmd
    networks:
      - dxspider_net

networks:
  dxspider_net:
    driver: bridge
#    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
#        - subnet: fd00:172:28::/64
